import type { QuizTemplate } from "./types.js";

export const PROGRAMMING_FUNDAMENTALS_V1: QuizTemplate = {
  id: "programming-fundamentals-v1",
  version: 1,
  title: "Programming Fundamentals — 10 questions",
  questions: [
    {
      id: "q01",
      order: 1,
      prompt: "let x = 3; x = x + 2; What is x?",
      options: [
        { id: "a", label: "3" },
        { id: "b", label: "5" },
        { id: "c", label: "6" },
        { id: "d", label: "error" },
      ],
      correctOptionId: "b",
      explanation: "The assignment replaces the old value with 3 + 2.",
      difficulty: "basic",
      durationMs: 30_000,
    },
    {
      id: "q02",
      order: 2,
      prompt: "What is the type of true?",
      options: [
        { id: "a", label: "string" },
        { id: "b", label: "number" },
        { id: "c", label: "boolean" },
        { id: "d", label: "object" },
      ],
      correctOptionId: "c",
      explanation: "true and false are boolean values.",
      difficulty: "basic",
      durationMs: 30_000,
    },
    {
      id: "q03",
      order: 3,
      prompt: "What does if (7 > 10) { A } else { B } select?",
      options: [
        { id: "a", label: "A" },
        { id: "b", label: "B" },
        { id: "c", label: "both" },
        { id: "d", label: "neither" },
      ],
      correctOptionId: "b",
      explanation: "7 > 10 is false, so the else branch runs.",
      difficulty: "basic",
      durationMs: 30_000,
    },
    {
      id: "q04",
      order: 4,
      prompt: "How many times does for (let i = 0; i < 4; i++) run?",
      options: [
        { id: "a", label: "3" },
        { id: "b", label: "4" },
        { id: "c", label: "5" },
        { id: "d", label: "infinitely" },
      ],
      correctOptionId: "b",
      explanation: "It runs for i = 0, 1, 2, 3.",
      difficulty: "basic",
      durationMs: 30_000,
    },
    {
      id: "q05",
      order: 5,
      prompt: "function triple(n) { return n * 3; } What is triple(4)?",
      options: [
        { id: "a", label: "7" },
        { id: "b", label: "12" },
        { id: "c", label: "16" },
        { id: "d", label: "undefined" },
      ],
      correctOptionId: "b",
      explanation: "The function returns its input multiplied by three.",
      difficulty: "basic",
      durationMs: 30_000,
    },
    {
      id: "q06",
      order: 6,
      prompt: "Given const a = [10, 20, 30], what is a[1]?",
      options: [
        { id: "a", label: "10" },
        { id: "b", label: "20" },
        { id: "c", label: "30" },
        { id: "d", label: "undefined" },
      ],
      correctOptionId: "b",
      explanation: "Array indexes begin at zero.",
      difficulty: "intermediate",
      durationMs: 30_000,
    },
    {
      id: "q07",
      order: 7,
      prompt: "Given const user = { name: 'Ada', level: 1 }; user.level = 2; what is user.name?",
      options: [
        { id: "a", label: "Ada" },
        { id: "b", label: "1" },
        { id: "c", label: "2" },
        { id: "d", label: "undefined" },
      ],
      correctOptionId: "a",
      explanation: "Updating one object property does not change another property.",
      difficulty: "intermediate",
      durationMs: 30_000,
    },
    {
      id: "q08",
      order: 8,
      prompt: "const a = { score: 1 }; const b = a; b.score = 4; What is a.score?",
      options: [
        { id: "a", label: "1" },
        { id: "b", label: "4" },
        { id: "c", label: "undefined" },
        { id: "d", label: "error" },
      ],
      correctOptionId: "b",
      explanation: "Both variables refer to the same object.",
      difficulty: "difficult",
      durationMs: 45_000,
    },
    {
      id: "q09",
      order: 9,
      prompt: "A loop runs n times and another loop inside it also runs n times. What is the usual time complexity?",
      options: [
        { id: "a", label: "O(1)" },
        { id: "b", label: "O(n)" },
        { id: "c", label: "O(n log n)" },
        { id: "d", label: "O(n²)" },
      ],
      correctOptionId: "d",
      explanation: "The body executes roughly n × n times.",
      difficulty: "difficult",
      durationMs: 45_000,
    },
    {
      id: "q10",
      order: 10,
      prompt: "What must be true before using binary search correctly?",
      options: [
        { id: "a", label: "The list is sorted" },
        { id: "b", label: "The list has no duplicates" },
        { id: "c", label: "The list is all numbers" },
        { id: "d", label: "The list has exactly 10 items" },
      ],
      correctOptionId: "a",
      explanation: "Binary search discards half based on ordering.",
      difficulty: "difficult",
      durationMs: 45_000,
    },
  ],
};
