import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import type { PublicRoomState } from "@codexwars/shared";
import { BattleStatsPanel } from "../components/BattleStatsPanel";
import { colors } from "../components/theme";

export function ParticipantQuizResultsScreen({ onContinue, onLeave, participantId, room }: { onContinue: () => void; onLeave: () => void; participantId: string; room: PublicRoomState }) {
  const player = room.players[participantId];
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.kicker}>QUIZ COMPLETE</Text><Text accessibilityRole="header" style={styles.title}>Knowledge becomes power.</Text><Text style={styles.copy}>{player?.displayName ?? "Participant"}, you scored {player?.correctAnswers ?? 0} out of {room.quiz.questionCount}. Your server-calculated shield is locked for the battle.</Text><View style={styles.score}><Text style={styles.scoreValue}>{player?.correctAnswers ?? 0}<Text style={styles.scoreTotal}> / {room.quiz.questionCount}</Text></Text><Text style={styles.scoreLabel}>CORRECT ANSWERS</Text></View>{player ? <BattleStatsPanel label="Battle powers earned" player={player} /> : null}<Pressable accessibilityRole="button" onPress={onContinue} style={styles.primary}><Text style={styles.primaryText}>Choose character  →</Text></Pressable><Pressable accessibilityRole="button" onPress={onLeave} style={styles.secondary}><Text style={styles.secondaryText}>Leave War Room</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, content: { flexGrow: 1, justifyContent: "center", padding: 22 }, kicker: { color: colors.success, fontSize: 11, fontWeight: "900", letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 38, fontWeight: "900", letterSpacing: -1.2, lineHeight: 43, marginTop: 10 }, copy: { color: colors.inkMuted, fontSize: 15, lineHeight: 22, marginTop: 12 }, score: { alignItems: "center", backgroundColor: colors.surfaceStrong, borderRadius: 16, marginVertical: 20, padding: 22 }, scoreValue: { color: colors.ink, fontSize: 46, fontWeight: "900" }, scoreTotal: { color: colors.inkMuted, fontSize: 22 }, scoreLabel: { color: colors.success, fontSize: 10, fontWeight: "900", letterSpacing: 1, marginTop: 5 }, primary: { alignItems: "center", backgroundColor: colors.accent, borderRadius: 13, justifyContent: "center", marginTop: 18, minHeight: 56 }, primaryText: { color: colors.ink, fontSize: 15, fontWeight: "900" }, secondary: { alignItems: "center", justifyContent: "center", minHeight: 52 }, secondaryText: { color: colors.inkMuted, fontSize: 14, fontWeight: "800" } });
